### ISSUE TITLE
Trouble compiling with rollup

### ISSUE THREAD

**Issue by ScottMaclure** [jikkai/svelte-router#2]
Windows 10, node 6.0.0

```
Error: Error: 'default' is not exported by node_modules\svelte-router\lib\svelte-router.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src\HelloWorld.html (1:7)
1: import SvelteRouter from 'svelte-router'
```

Using:
```
+-- rollup@0.45.2
+-- svelte-cli@1.3.7
+-- rollup-plugin-commonjs@8.0.2
+-- rollup-plugin-node-resolve@3.0.0
+-- rollup-plugin-svelte@3.0.1
+-- rollup-watch@4.3.1
`-- svelte-router@1.0.1
```

`svelte-router/blob/master/src/index.js` is different from npm installed `node_modules/svelte-router/lib/svelte-router.js`? Investigating...

Using a tilde in an import statement is a webpack specific thing? e.g. `import createRouter from '~utils/create-router'` (from https://stackoverflow.com/a/39535907)

**Comment by jikkai** [comment]
I forgot to set the library target! 😂 Sorry about that.

**Comment by qubyte** [comment]
I'm seeing this error too. Same issue?
