### ISSUE TITLE
Do we need to supply routes in an object and as declarations?

### ISSUE THREAD

**Issue by matt3224** [jikkai/svelte-router#3]
Hi,

I'm looking at using your router but am wondering why I need to supply routes both declaratively `<RouterLink>` and as an object `createRouter({})`

![screen_shot_2017-09-23_at_3_46_22_pm](https://user-images.githubusercontent.com/2401925/30774202-c299355a-a076-11e7-8723-8077c5f8de92.png)

Thanks

**Comment by jikkai** [comment]
`createRouter({})` help us define some routes.

`<RouterLink>` is just a component for rendering as an <a> tag. Passing the `to` prop to specify its link.
