### ISSUE TITLE
Is there a way to pass data into route components?

### ISSUE THREAD

**Issue by glomotion** [jikkai/svelte-router#5]
Hey there!
So i'm kinda new to Svelte js - and am experimenting with using it for a small upcoming project.
Just wondering if there's a trick to getting the store to be passed down to the route 
components...?

I'm currently using: "svelte: ^1.47.1"

Store is currently created and passed into the app like so:
index.js (webpack entry):
```
import App from './app.html';
import { Store } from 'svelte/store.js';

const store = new Store({
  animal: 'dog',
  sheep: 'baaah',
});

const app = new App({
  target: document.body,
  store,
});

export default app;
```

app.html:
```
<div>
  <RouterLink to="/">Home</RouterLink>
  <RouterLink to="/welcome">Welcome</RouterLink>
  <h1>animal: {{$animal}}</h1>
  <div id="app"></div>
</div>

<script>
  import { createRouter, RouterLink } from 'svelte-router'
  import Home from './home.html'
  import Welcome from './welcome.html'

  const router = createRouter({
    '/': Home,
    '/welcome': Welcome
  });

  export default {
    oncreate () {
      console.log(this.store.get('animal')); // "dog"
      router.create('#app');
    },

    ondestroy () {
      router.destroy()
    },

    components: { 
    	RouterLink, Home, Welcome
    }
  }
</script>
```
home.html:
```
<h1>home page!</h1>
<script>
export default {
  oncreate () {
    console.log(this.store.get('animal')); // undefined
  },
}
</script>
```

inside app.html: 
`<h1>animal: {{$animal}}</h1>`
renders as: 
`<h1>animal: dog</h1>`
as expected.

If i try and access:
`<div>{{$animal}}</div>` 
from home.html, i get the following error:
`Uncaught TypeError: Cannot read property '_init' of undefined`

**Comment by glomotion** [comment]
Actually, it would also be awesome to know how to pass other props down to Route components...?

ATM, it looks like Route components are completely isolated from any options / state / store data that exists in the app where the router is configured (in my case, app.html).

**Comment by glomotion** [comment]
#https://github.com/jikkai/svelte-router/pull/6

**Comment by jikkai** [comment]
😀 Merged.
